package gojup

import "encoding/json"

const ALL = "https://token.jup.ag/all"
const STRICT = "https://token.jup.ag/strict"

// autogenerated
type Token struct {
	Address  string   `json:"address"`
	ChainID  int      `json:"chainId"`
	Decimals int      `json:"decimals"`
	Name     string   `json:"name"`
	Symbol   string   `json:"symbol"`
	LogoURI  string   `json:"logoURI"`
	Tags     []string `json:"tags"`
}

func GetTokenlist(urlstring string) (map[string]Token, error) {
	result := make(map[string]Token)
	b, err := Get(urlstring)
	if err != nil {
		return result, err
	}
	results := make([]Token, 0)
	err = json.Unmarshal(b, &results)
	if err != nil {
		return result, err
	}
	for _, item := range result {
		result[item.Address] = item
	}
	return result, nil
}

func GetTokenlistAll() (map[string]Token, error) {
	return GetTokenlist(ALL)
}

func GetTokenlistStrict() (map[string]Token, error) {
	return GetTokenlist(STRICT)
}
